repositories:
  remote:
   - http://repo1.maven.org/maven2

artifacts:
  javax_javaee: javax:javaee-api:jar:7.0
  commons_io: commons-io:commons-io:jar:1.4

  junit: junit:junit:jar:3.8.1
  mockito: org.mockito:mockito-all:jar:1.9.5
